### ISSUE TITLE
gdbserver build failed

### ISSUE THREAD

**Issue by agostrer** [foss-for-synopsys-dwc-arc-processors/gdb#16]
Hi Anton,

I am trying to build the gdbserver on a Linux host (uname -a
Linux alex-ThinkPad 3.9.0-030900-generic #201304291257 SMP Mon Apr 29 16:58:15 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux). 
So I added the "/home/agostrer/work/mbr-alex/staging/toolchain/bin" to the PATH and invoked the following command:

./gdb/gdbserver/configure --host=i686-pc-linux-gnu --target=arc-linux-uclibc --prefix=/ --disable-werror

A Makefile was generated and no error was printed. But the next step failed:
"make
Makefile:26: *** missing separator.  Stop."

Here are these lines:
"   24 # First, test for a proper version of make, but only where one is required.
   25 
   26 @if gcc
   27 ifeq (,$(.VARIABLES)) # The variable .VARIABLES, new with 3.80, is never empty.
   28 $(error GNU make version 3.80 or newer is required.)
   29 endif
   30 @endif
   31 
  32 # -------------------------------
   33 # Standard Autoconf-set variables
   34 # -------------------------------
   35 VPATH=./gdb/gdbserver
   36 
   37 build_alias=@build_noncanonical@
   38 build_vendor=unknown
   39 build_os=linux-gnu
   40 build=x86_64-unknown-linux-gnu
   41 host_alias=@host_noncanonical@
   42 host_vendor=pc
   43 host_os=linux-gnu
   44 host=i686-pc-linux-gnu
   45 target_alias=@target_noncanonical@
   46 target_vendor=unknown
   47 target_os=linux-uclibc
   48 target=arc-unknown-linux-uclibc
   49 
   50 program_transform_name = s&^&arc-linux-uclibc-&
   51 
   52 prefix = /
"
I am using "GNU Make 3.81", "gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)", "gcc version 4.4.7 (ARCompact Linux uClibc toolchain (built 20130529))"
What might be the problem?

Thank you,
Alex.

**Comment by anthony-kolesov** [comment]
I think that can be closed now.
